### ISSUE TITLE
Prompt remains stuck on the screen

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/vorp_fishing-lua#2]
With vorp_fishing, I am seeing an issue once you catch a fish. If you keep it, the prompt will be removed but when you throw the fish back, the prompt remains stuck on the screen. Everything else within the script seems to be working just fine

**Comment by creativewild** [comment]
I will fix this shortly

**Comment by creativewild** [comment]
#1
#3 This should solve your issue once merged @RizzooTv

**Comment by DerHobbs** [comment]
I just tested it, the problem persists, if you throw the fish back into the water, the display doesn't go away

https://prnt.sc/KVZYDYRN0Cgw

**Comment by creativewild** [comment]
> I just tested it, the problem persists, if you throw the fish back into the water, the display doesn't go away
> 
> https://prnt.sc/KVZYDYRN0Cgw

did you cleared the cache just in case?

I have tested on a fresh vorp install, I will add some debug calls so we can find if there's anything preventing the prompt of going away

**Comment by DerHobbs** [comment]
I've tried, unfortunately without success

**Comment by RizzooTv** [comment]
Yes unchanged for me too, it still doesn't go away when you release the fish

**Comment by creativewild** [comment]
@RizzooTv  @DerHobbs  try this fix please #4

**Comment by XCIV-DEV** [comment]
please fix this issue

**Comment by DerHobbs** [comment]
it is fixed

**Comment by creativewild** [comment]
@pattiemo update you version, if you keep using the pre-made you will have the issue
