### ISSUE TITLE
Bait Shop Giving Default Options for "Food" and "Tools" menus

### ISSUE THREAD

**Issue by agostino-c** [VORPCORE/vorp_fishing-lua#21]
I installed VORP through the txAdmin recipe, and everything works wonderfully except for when I go to the Fishing Stores, the items are the default ones. I've tried finding the configuration for this in the resource with no luck. I even tried doing a fresh install of the fishing resource as well. I have attached a screenshot for reference. Is there something I'm able to configure outside of the fishing resource for this? Or should I just use the stores resource to make my own?
![image](https://github.com/VORPCORE/vorp_fishing-lua/assets/165092191/3cfed11c-3a85-46bd-b755-c36391da81a2)

**Comment by James-the-Coding-Gamer** [comment]
> I installed VORP through the txAdmin recipe, and everything works wonderfully except for when I go to the Fishing Stores, the items are the default ones. I've tried finding the configuration for this in the resource with no luck. I even tried doing a fresh install of the fishing resource as well. I have attached a screenshot for reference. Is there something I'm able to configure outside of the fishing resource for this? Or should I just use the stores resource to make my own? ![image](https://private-user-images.githubusercontent.com/165092191/345715452-3cfed11c-3a85-46bd-b755-c36391da81a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzYyNDgsIm5iZiI6MTcyMDA3NTk0OCwicGF0aCI6Ii8xNjUwOTIxOTEvMzQ1NzE1NDUyLTNjZmVkMTFjLTNhODUtNDZiZC1iNzU1LWMzNjM5MWRhODFhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwNjUyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTNjMmViY2IwZTZkNzE1OGZlNTk0OGFkZDkxOWFhNjMyNDg3NDExYTlmNTk2MWQ4Y2ViMTQzZmExYmUzNGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6rY4vav_y1_cuFlG2RHGTPxh8eQf7JR25F645CGANEE)

that becuse the shop is in vorp_stores  not the fishing script 

![image](https://github.com/VORPCORE/vorp_fishing-lua/assets/26008458/808d8f70-d083-4c72-870e-a8e5182ec71e)
https://github.com/VORPCORE/vorp_stores-lua/blob/main/config.lua
@austin-cefalu
