### ISSUE TITLE
Problems with catch the fish

### ISSUE THREAD

**Issue by SkazyPlayGames** [VORPCORE/vorp_fishing-lua#6]
I have all baits add from sql and name is same.
but fish wont take bait  and i cant catch the fish .

**Comment by creativewild** [comment]
Could you make a small video of the issue?

for the fish to hook there are two conditions, you need to have the fish near the bait/hook and you need to press the mouse button for the Hook functionality, the fish wont hook itself :)

Let me know if this helps

**Comment by SkazyPlayGames** [comment]
I find the way i need to pres left click, but problem is that i cant see when fish is on bait i spaming the left click 🗡️

**Comment by SkazyPlayGames** [comment]
when is night is  more harder i cant see when is fish close to the bait i just spaming left click and i hope fish is close to the bait ..

**Comment by SkazyPlayGames** [comment]
problem is not big just add something to know when fish is close to the bait to press left click to catch the fish and that is it.

**Comment by creativewild** [comment]
@SkazyPlayGames the fish is attracted to the baite when you do the action of "hook" if you don't do it, the fish will not bite.

I will see about adding a notification saying fishes are within range

**Comment by creativewild** [comment]
also you can use 3rd eye (mid mouse click) to see the fish in the water

**Comment by MartensMalsero** [comment]
> also you can use 3rd eye (mid mouse click) to see the fish in the water

@creativewild When the bait is in the water you can no longer use the 3rd eye. 


> I will see about adding a notification saying fishes are within range

@creativewild if this is possible, we can let the fish bite automatically

**Comment by creativewild** [comment]
> > also you can use 3rd eye (mid mouse click) to see the fish in the water
> 
> @creativewild When the bait is in the water you can no longer use the 3rd eye.  

This was mention on a before fishing scenario not while fishing, there's also a debug option you can enable on the config that will show a line above all fished swimming around 

> > I will see about adding a notification saying fishes are within range
> 
> @creativewild if this is possible, we can let the fish bite automatically

this is planned to be added soon
