### ISSUE TITLE
when you decided to thro the fish the menu doesnt disappeared 

### ISSUE THREAD

**Issue by XCIV-DEV** [VORPCORE/vorp_fishing-lua#8]
when you decided to thro the fish the menu doesnt disappeared 

![image](https://user-images.githubusercontent.com/95479446/162417760-4b4c4c72-eac6-4a66-aff3-87332eb327b7.png)

**Comment by creativewild** [comment]
this was already fixed
Update your version

**Comment by creativewild** [comment]
same as on the other comment you made @pattiemo
